Improve subscription validation for fees
forta-network/forta-node pull request #687
Opened 2023-04-08 07:12 UTC by aomerk

2023-04-10 10:00 UTC, canercidam requested changes
Great stuff! It's really good that we are reusing the authentication mechanism and not duplicating it. Feels like we can do some polishing.

2023-04-10 10:02 UTC, aomerk commented on services/scanner/combiner_stream.go
> +			log.WithError(err).Warnf("can not add subscription %s", subscription)
alert feed will then store that subscription and start querying/feeding subscribed bots. That is an existing mechanism, just improved error handling to support validation

2023-04-10 10:25 UTC, aomerk commented on clients/authenticator.go
> +	rateLimiting := cfg.JsonRpcProxy.RateLimitConfig
Nice catch, comes from the copy/paste. removed with e6a9924ae59e9ce15554782d8d4143586e0803e9

2023-04-10 10:25 UTC, aomerk commented on clients/authenticator.go
> +func NewBotAuthenticator(ctx context.Context, cfg config.Config) (IPAuthenticator, error) {
same as above, removing the redundancy made it possible to remove that as well. fixed with e6a9924ae59e9ce15554782d8d4143586e0803e9

2023-04-10 10:27 UTC, aomerk commented on tests/e2e/deps-start.sh
> +./mock-graphql-api &
Loved this, great idea. I wasn't aware of that thing at all

2023-04-10 10:48 UTC, aomerk commented on tests/e2e/deps-start.sh
> +./mock-graphql-api &
can you check this commit out? 6f0a0f1694f2478173230b51547a05b7af689d99

2023-04-10 11:59 UTC, canercidam commented on services/scanner/combiner_stream.go
> +			log.WithError(err).Warnf("can not add subscription %s", subscription)
I mean, what kind of output does `Warnf("can not add subscription %s", subscription)` generate? That doesn't look immediately `%s`able.

If we are able to pick an identifier that is short enough, maybe `WithField(...).Warn()` could be more useful - not sure, though.

2023-04-10 12:01 UTC, canercidam commented on clients/messaging/client.go
> +		logger.Tracef("received: %s", string(m.Data))
I don't know if debug is better or not, I guess it fits in both. I agree that it can be annoyingly noisy.

2023-04-10 12:01 UTC, canercidam commented on tests/e2e/deps-start.sh
> +./mock-graphql-api &
Awesome, looks great. Thanks! :slightly_smiling_face:

2023-04-11 07:59 UTC, aomerk commented on clients/authenticator.go
> +	server       *http.Server
resolved: d56487a418583fedbe7d954a153c2c610d8cd7d8

2023-04-11 08:10 UTC, aomerk commented on services/scanner/combiner_stream.go
> +			log.WithError(err).Warnf("can not add subscription %s", subscription)
resolved with c4c4a1ae9f6dfed66ef1531cea622665e116131d

2023-04-11 08:11 UTC, canercidam approved these changes

2023-04-11 08:21 UTC, merged